mywebsite/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from filebrowser.sites import site

from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.ico')),  # https://favicon.io/favicon-generator/
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include('django_otp.urls')),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
    path('maintenance-mode/', include('maintenance_mode.urls')),
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name='admin-manual'),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite_home/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.urls import path

from mywebsite_blog import views as blogviews

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='index'),
    path('set_language', views.set_language, name='set_language'),
    path('search', views.SearchListView.as_view(), name='search'),
    path('contact', views.ContactView.as_view(), name='contact')
]

# add AJAX based blog articles dynamically
for item in blogviews.getSlugByMenuItemName(None):
    # extract url and name
    url = item['slug']
    name = item['name'].replace('Item ', '')

    # add path to urlpatterns
    urlpatterns.append(path(url, blogviews.AjaxArticleDetailView.as_view(link_name=name), name=name))

mywebsite_home/forms.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from captcha.fields import CaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm
from reversion.models import Version

from mywebsite.utils.widgets import AceWidget, JSONEditorWidget, TinyMCEWidget
from mywebsite_antispam.honeypot.forms import HoneypotField
from mywebsite_antispam.spamdetector.forms import SpamDetectorField

from . import models


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    url = HoneypotField()
    message = SpamDetectorField(required=True, widget=forms.Textarea, max_length=2048)
    captcha = CaptchaField()  # required=True must be set via jQuery in template, because of CaptchaField

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'ajax-form-contact'
        self.helper.form_class = 'form-validate well'
        self.helper.form_method = 'POST'
        self.helper.form_action = reverse('home:contact')
        self.helper.attrs.update({'novalidate': ''})
        # translation for fields
        self.fields['contact_name'].label = _('contact_name')
        self.fields['contact_email'].label = _('contact_email')
        self.fields['message'].label = _('contact_message')
        self.fields['captcha'].label = _('contact_captcha')
        # add submit button
        self.helper.add_input(Submit('submit', _("CONTACT_SUBMIT"), css_class="btn btn-dark text-white"))


class NewsAdminForm(TranslatableModelForm):
    body = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ))

    class Meta:
        model = models.News
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(NewsAdminForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = _('body_field')


class ScriptsEditorAdminForm(forms.ModelForm):
    class Meta:
        model = models.WebsiteSettingsScripts
        widgets = {
            'body': AceWidget(
                mode="css",
                theme="tomorrow_night_eighties",
                width="100%",
                height="500px",
                showprintmargin=True,
            ),
        }
        exclude = ()


class VersionAdminForm(forms.ModelForm):
    class Meta:
        model = Version
        widgets = {
            'serialized_data': JSONEditorWidget
        }
        exclude = ()

mywebsite_home/views.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

import os
from datetime import datetime
from itertools import chain
from operator import attrgetter

from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.template.context_processors import csrf
from django.template.loader import get_template
from django.urls import translate_url
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views import generic
from django.views.decorators.csrf import requires_csrf_token

from crispy_forms.utils import render_crispy_form
from django_filters.views import FilterView

from mywebsite.utils.tools import LazyEncoder, get_default_language
from mywebsite_antispam import models as antispammodels
from mywebsite_blog import models as blogmodels
from mywebsite_blog import views as blogviews
from mywebsite_home.templatetags.core_settings_tags import getTemplateByName

from .filters import ArticleFilter
from .forms import ContactForm
from .models import News


class NewsListView(blogviews.ArticleCommonDataMixin, generic.ListView):
    model = News
    context_object_name = 'news_list'
    template_name = 'home/index.html'
    paginate_by = settings.PAGINATION_NEWS
    paginator_class = blogviews.CustomPaginator

    def render_to_response(self, context, **response_kwargs):
        response = super(NewsListView, self).render_to_response(context, **response_kwargs)
        # set cookie for FORCE_SCRIPT_NAME setting, because this is used for TinyMCE CustomFileBrowser's callback
        response.set_cookie("force_script_name", settings.FORCE_SCRIPT_NAME)
        return response

    def get_queryset(self):
        queryset = super(NewsListView, self).get_queryset()
        # standard filter for News
        news_queryset = queryset.active_translations().distinct().filter(
            is_published=True, is_archived=False, date__lte=datetime.now())
        # addidtional filter for Articles, which should be shown in news list
        article_queryset = blogmodels.Article.objects.active_translations().distinct().filter(is_onnewsfeed=True,
                                                                                              is_internal=False,
                                                                                              is_published=True,
                                                                                              is_archived=False,
                                                                                              date__lte=datetime.now())
        # combine both querysets and sort with date desc
        queryset = sorted(chain(news_queryset, article_queryset), key=attrgetter('date'), reverse=True)
        return queryset


def set_language(request):
    """
    Redirect to a given URL while setting the chosen language in the session or
    cookie. The URL and the language code need to be specified in the request
    parameters.

    Since this view changes how the user will see the rest of the site, it must
    only be accessed as a POST request. If called as a GET request, it will
    redirect to the page in the request (the 'next' parameter) without changing
    any state.
    """
    next = request.POST.get('next', request.GET.get('next'))
    if not next:
        next = request.META.get('HTTP_REFERER', None)
    if not next:
        next = '/'
    response = HttpResponseRedirect(next) if next else HttpResponse(status=204)
    if request.method == 'POST':
        lang_code = request.POST.get('language', get_default_language())
        if lang_code:
            if next:
                next_trans = translate_url(next, lang_code)
                if next_trans != next:
                    response = HttpResponseRedirect(next_trans)
            if hasattr(request, 'session'):
                request.session[translation.LANGUAGE_SESSION_KEY] = lang_code
            # Always set cookie
            response.set_cookie(
                settings.LANGUAGE_COOKIE_NAME, lang_code,
                max_age=settings.LANGUAGE_COOKIE_AGE,
                path=settings.LANGUAGE_COOKIE_PATH,
                domain=settings.LANGUAGE_COOKIE_DOMAIN,
            )
            # Switch language for current thread
            translation.activate(lang_code)
    return response


# added custom view for manual
# see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
@staff_member_required
def manual(request):
    return render(request, 'admin_doc/admin_manual.html', {'title': _('Manual')})


@method_decorator(requires_csrf_token, name='dispatch')
class ContactView(blogviews.ArticleCommonDataMixin, generic.edit.FormView):
    template_name = 'home/contact.html'
    form_class = ContactForm
    success_url = '/contact'

    def form_invalid(self, form):
        response = super().form_invalid(form)

        if self.request.is_ajax():
            if form.has_error('url', code='spam-protection') or form.has_error('message', code='spam-protection'):
                contact_name = self.request.POST.get('contact_name', '')
                contact_email = self.request.POST.get('contact_email', '')
                form_message = self.request.POST.get('message', '')

                # Add sender to AntiSpamTrainingData
                last_spam = antispammodels.AntiSpamTrainingData.objects.filter(
                    text=form_message).last()
                spam_dataset = antispammodels.AntiSpamTrainingData.objects.get(pk=last_spam.pk)
                if spam_dataset:
                    spam_dataset.sender = '{} ({})'.format(contact_name, contact_email)
                    spam_dataset.save()
                # Fake successful sending
                data = {'message': _('Message sent successfully!'), 'success': True}
                return JsonResponse(data, encoder=LazyEncoder)
            else:
                # ensure CSRF token is placed in, before using render_crispy_form
                ctx = {}
                ctx.update(csrf(self.request))
                # render AJAX response with django-crispy-forms
                html_form = render_crispy_form(form, context=ctx)
                data = {'message': _('Please correct the error below.'), 'html_form': html_form, 'success': False}
                return JsonResponse(data, encoder=LazyEncoder)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.is_ajax():
            form = ContactForm(self.request.POST)

            # Validate the form: the captcha field will automatically
            # check the input
            human = True
            contact_name = self.request.POST.get('contact_name', '')
            contact_email = self.request.POST.get('contact_email', '')
            form_message = self.request.POST.get('message', '')

            # Add sender to AntiSpamTrainingData
            last_spam = antispammodels.AntiSpamTrainingData.objects.filter(
                text=self.request.POST['message']).last()
            spam_dataset = antispammodels.AntiSpamTrainingData.objects.get(pk=last_spam.pk)
            if spam_dataset:
                spam_dataset.sender = '{} ({})'.format(contact_name, contact_email)
                spam_dataset.save()

            # 1) Send Email to Admin
            # Build Email structure with the contact information
            template_dict = getTemplateByName('Template contact')
            template = template_dict['template']
            if not template:
                template = get_template('home/contact-template.txt')
            mail_subject = template_dict['subject'].render()
            if not mail_subject:
                mail_subject = settings.DEFAULT_SUBJECT
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_message': form_message,
            }
            content = template.render(context)
            email = EmailMessage(
                subject=mail_subject,
                body=content,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[settings.DEFAULT_TO_EMAIL]
            )
            email.send()

            # 2) Send Email response to sender
            # Build Email structure with the contact information
            template_dict = getTemplateByName('Template contact-response')
            template = template_dict['template']
            if not template:
                template = get_template('home/contact-response-template.txt')
            mail_subject = template_dict['subject'].render()
            if not mail_subject:
                mail_subject = settings.DEFAULT_SUBJECT
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_message': form_message,
            }
            content = template.render(context)
            email = EmailMessage(
                subject=mail_subject,
                body=content,
                from_email=settings.DEFAULT_FROM_EMAIL,
                to=[contact_email]
            )
            email.send()

            data = {'message': _('Message sent successfully!'), 'success': True}
            return JsonResponse(data, encoder=LazyEncoder)

        else:
            return response

mywebsite_home/templates/home/includes/bottom-content.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static websettings_tags %}

{% block content %}
<div class="container_12">
    <div
        class="grid_4"
        data-scrollreveal="enter from the top after 0.3s ease-out"
        style="-webkit-transform: translatey(-24px);-moz-transform: translatey(-24px);transform: translatey(-24px);opacity: 0;"
        data-scrollreveal-initialized="true"
    >
        <div class="block">
            <div class="moduletable-icon-noicon ">
                <h1>{% transFromWebSettings "BOTTOMCONTENT_01_HEADING" %}</h1>
                <div class="clr">
                </div>
                <br />
                <div class="custom">
                    <span>{% transFromWebSettings "BOTTOMCONTENT_01_PARA" %}</span>
                </div>
            </div>
        </div>
    </div>
    <div
        class="grid_4"
        data-scrollreveal="enter from the top after 0.6s ease-out"
        style="-webkit-transform: translatey(-24px);-moz-transform: translatey(-24px);transform: translatey(-24px);opacity: 0;"
        data-scrollreveal-initialized="true"
    >
        <div class="block">
            <div class="moduletable-icon-noicon ">
                <h1>{% transFromWebSettings "BOTTOMCONTENT_02_HEADING" %}</h1>
                <div class="clr">
                </div>
                <br />
                <div class="custom">
                    <span>{% transFromWebSettings "BOTTOMCONTENT_02_PARA" %}</span>
                </div>
            </div>
        </div>
    </div>
    <div
        class="grid_4"
        data-scrollreveal="enter from the top after 0.9s ease-out"
        style="-webkit-transform: translatey(-24px);-moz-transform: translatey(-24px);transform: translatey(-24px);opacity: 0;"
        data-scrollreveal-initialized="true"
    >
        <div class="block">
            <div class="moduletable-icon-noicon ">
                <h1>{% transFromWebSettings "BOTTOMCONTENT_03_HEADING" %}</h1>
                <div class="clr">
                </div>
                <br />
                <div class="custom">
                    <span>{% transFromWebSettings "BOTTOMCONTENT_03_PARA" %}</span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mywebsite_home/templates/home/includes/dsad-dev-link.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<a
    href="https://dsoft-app-dev.de"
    target="_blank"
>
    <span style="text-transform: uppercase; letter-spacing: 1px; background-color: #131313;">
        <span style="color: #9cdcf7;">{D}</span>
        <span style="color: #fff;">S</span>
        <span style="color: #fff;">A</span>
        <span style="color: #fff;">D</span>
    </span>
</a>
{% endblock %}

mywebsite_home/templates/home/includes/menu-submenu.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


<ul class="navig">
    {% for item in items %}
    {% if item.visible %}
    <li class="{% if item.children %}deeper parent{% endif %}">
        <a href="{{ item.url }}">{{ item.title }}</a>
        {% if item.children %}
        {% with items=item.children template_name='home/includes/menu-submenu.html' %}
        {% include template_name %}
        {% endwith %}
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
</ul>

mywebsite_home/templates/home/includes/menu.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}

<ul
    id="menu"
    class="menu"
>
    <li id="toggle">
        <a href="#menu">
            <i class="fa fa-align-justify"></i>
        </a>
    </li>
    <li id="hide">
        <a href="#toggle">
            <i class="fa fa-align-justify"></i>
        </a>
    </li>
    {% for item in menu %}
    {% if item.visible %}
    <li class="{% if item.title == selected_menu_parent.title %}current active{% endif %} {% if item.children %}deeper parent{% endif %}">
        <a href="{{ item.url }}">{{ item.title }}</a>
        {% if item.children %}
        {% include 'home/includes/menu-submenu.html' with items=item.children %}
        {% endif %}
    </li>
    {% endif %}
    {% endfor %}
    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}
    {% if languages|length > 1 %}
    {% for language in languages %}
    <form
        action="{% url 'home:set_language' %}"
        method="post"
        id="form_{{ language.code }}"
        style="display:inline!important;"
    >
        {% csrf_token %}
        <input
            name="next"
            type="hidden"
            value="{{ redirect_to }}"
        />
        <input
            name="language"
            type="hidden"
            value="{{ language.code }}"
        />
    </form>
    <li>
        <button
            class="lang-button-{{ language.code }}"
            type="submit"
            form="form_{{ language.code }}"
            value="Submit"
        ></button>
    </li>
    {% endfor %}
    {% endif %}
</ul>
{% endblock %}

mywebsite_home/templates/home/includes/meta-tags.html
<!-- HTML Meta Tags -->
{% load core_settings_tags websettings_tags %}
{% getCoreSettingItemsFor _('Meta Tag') 'HTML Tags' as object_list %}
{% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
        <meta name="{{ obj|getAttribItemKey }}" content="{{ obj|getAttribItemValue|handleWebSettingsType }}">
    {% endfor %}
{% endfor %}

<!-- Google / Search Engine Tags -->
{% getCoreSettingItemsFor _('Meta Tag') 'Google Tags' as object_list %}
{% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
        <meta itemprop="{{ obj|getAttribItemKey }}" content="{{ obj|getAttribItemValue|handleWebSettingsType }}">
    {% endfor %}
{% endfor %}

<!-- Facebook Meta Tags -->
{% getCoreSettingItemsFor _('Meta Tag') 'Facebook Tags' as object_list %}
{% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
        <meta property="{{ obj|getAttribItemKey }}" content="{{ obj|getAttribItemValue|handleWebSettingsType }}">
    {% endfor %}
{% endfor %}

<!-- Twitter Meta Tags -->
{% getCoreSettingItemsFor _('Meta Tag') 'Twitter Tags' as object_list %}
{% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
        <meta name="{{ obj|getAttribItemKey }}" content="{{ obj|getAttribItemValue|handleWebSettingsType }}">
    {% endfor %}
{% endfor %}

mywebsite_home/templates/home/includes/pagination.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

<div class="pagination justify-content-center">
    <span class="page-links">
        {% if page_obj.has_previous %}
        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}&searchword={{ searchword }}">
            {% trans "PAGE_PREV" %}</a>
        {% endif %}
        <span class="page-current">
            {% trans "PAGE_TEXT1" %} {{ page_obj.number }} {% trans "PAGE_TEXT2" %} {{ page_obj.paginator.num_pages }}
        </span> {% if page_obj.has_next %}
        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}&searchword={{ searchword }}">
            {% trans "PAGE_NEXT" %}</a> {% endif %}
    </span>
</div>

mywebsite_home/templates/home/includes/parallax-image.html
<!--
	Copyright (C) 2018 dsoft-app-dev.de and friends.

	This Program may be used by anyone in accordance with the terms of the
	German Free Software License

	The License may be obtained under http://www.d-fsl.org.
-->

{% load i18n static %} {% static "" as baseUrl %} {% block content %}
<div id="parallax-images">
	<div class="parallax bg images-parallax">
		<div class="content-p">
			<p>
				<span class="exemple" style="color: #fff; padding: 25px; font-weight: bold; text-transform: uppercase; letter-spacing: 5px; font-size: 45px;">
					<span style="color: #9cdcf7; text-transform: none;">{Daßler}</span>
					<span>
						<firstletter style="color: #9cdcf7;">S</firstletter>oftware & </span>
					<span>
						<firstletter style="color: #9cdcf7;">A</firstletter>pplication</span>
					<span>
						<firstletter style="color: #9cdcf7;">D</firstletter>evelopment</span>
				</span>
			</p>
		</div>
	</div>
</div>
{% endblock %}

mywebsite_home/templates/home/includes/parallax-slider.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static core_settings_tags websettings_tags %}

{% block content %}
<div class="carousel-slider cl-parallax">
    <div class="main cl-align-center">
        <div
            id="myCarouselIndicators"
            class="carousel slide cl-client-carousel"
            data-ride="carousel"
            data-pause="false"
            style="display: block; opacity: 1;"
        >
            {% getCoreSettingItemsFor _('Slider Item') 'Parallax-Slider' as object_list %}
            <ol class="carousel-indicators">
                {% for object in object_list %}
                <li
                    data-target="#myCarouselIndicators"
                    data-slide-to="{{ forloop.counter0 }}"
                    class="{% if forloop.first %}active{% endif %}"
                ></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                {% for object in object_list %}
                <div class="carousel-item client-carousel-item {% if forloop.first %}active{% endif %}">
                    {% if object.text %}
                    <figure>
                        <i class="{{ object.class|handleWebSettingsType }}"></i>
                    </figure>
                    <h3>{{ object.title|handleWebSettingsType }}</h3>
                    <p>{{ object.text|handleWebSettingsType }}</p>
                    {% elif object.src %}
                    <img
                        class="{{ object.class|handleWebSettingsType }}"
                        src="{{ object.src|handleWebSettingsType }}"
                        alt=".."
                    >
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            <a
                class="carousel-control-prev"
                href="#myCarouselIndicators"
                role="button"
                data-slide="prev"
            >
                <span
                    class="carousel-control-prev-icon"
                    aria-hidden="true"
                ></span>
                <span class="sr-only">{% trans "CAROUSEL_CTRL_PREV" %}</span>
            </a>
            <a
                class="carousel-control-next"
                href="#myCarouselIndicators"
                role="button"
                data-slide="next"
            >
                <span
                    class="carousel-control-next-icon"
                    aria-hidden="true"
                ></span>
                <span class="sr-only">{% trans "CAROUSEL_CTRL_NEXT" %}</span>
            </a>
        </div>
    </div>
</div>
{% endblock %}

mywebsite_home/templates/home/includes/search.html
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<form
    action="{% url 'home:search' %}"
    method="GET"
    id="search-form"
    class="form-inline"
>{% csrf_token %}
    <label
        for="popup-search-searchword"
        class="element-invisible"
    >{% trans "SEARCH_INFO_PARA" %}</label>
    <input
        name="searchword"
        id="popup-search-searchword"
        maxlength="200"
        class="inputbox search-query input-medium"
        type="search"
        placeholder="{% trans 'SEARCH_INFO_PLACEHOLDER' %}"
    >
</form>
{% endblock %}