mywebsite/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from filebrowser.sites import site

from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.ico')),  # https://favicon.io/favicon-generator/
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include('django_otp.urls')),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
    path('maintenance-mode/', include('maintenance_mode.urls')),
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name='admin-manual'),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite_blog/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.urls import include, path

from . import views

app_name = 'blog'

urlpatterns = [
    # Categories
    path('category', views.CategoryListView.as_view(), name='category'),
    path('category/<slug:category>', views.ArticleListView.as_view(), name='article-category-list'),

    # Tags
    path('tags/get-list-flat', views.get_tags_list_flat_jx, name='get-tags-list-flat'),
    path('tags/<tagname>', views.ArticleListView.as_view(), name='article-tag-list'),

    # Articles
    path('', views.ArticleListView.as_view(), name='blog'),
    path('<slug:slug>', views.ArticleDetailView.as_view(), name='article-detail'),
    path('<slug:slug>/compare', views.ArticleHistoryCompareDetailView.as_view(), name='compare-article'),
]

mywebsite_home/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.urls import path

from mywebsite_blog import views as blogviews

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='index'),
    path('set_language', views.set_language, name='set_language'),
    path('search', views.SearchListView.as_view(), name='search'),
    path('contact', views.ContactView.as_view(), name='contact')
]

# add AJAX based blog articles dynamically
for item in blogviews.getSlugByMenuItemName(None):
    # extract url and name
    url = item['slug']
    name = item['name'].replace('Item ', '')

    # add path to urlpatterns
    urlpatterns.append(path(url, blogviews.AjaxArticleDetailView.as_view(link_name=name), name=name))

mywebsite_home/models.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 - 2022 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from jsonfield import JSONField
from parler.models import TranslatableModel, TranslatedFields
from reversion.models import Version
from tinymce.models import HTMLField


# Abstract model
class TimeStampedModelMixin(models.Model):
    """
    Abstract Mixin model to add timestamp
    """
    # Timestamp
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created_field')
    )
    updated = models.DateTimeField(
        auto_now=True,
        db_index=True,
        verbose_name=_('updated_field')
    )

    class Meta:
        abstract = True


# Hint: Making existing fields translatable,
# see https://django-parler.readthedocs.io/en/latest/advanced/migrating.html
class News(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(
            max_length=191,
            verbose_name=_('title_field')
        ),
        body=HTMLField(
            default='',
            verbose_name=_('body_field')
        )
    )
    date = models.DateField(
        default=now,
        verbose_name=_('date_field')
    )
    author = models.CharField(
        max_length=80,
        blank=True,
        verbose_name=_('author_field')
    )
    is_body_title_hidden = models.BooleanField(
        default=False,
        verbose_name=_('is_body_title_hidden_field')
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name=_('is_published_field')
    )
    is_archived = models.BooleanField(
        default=False,
        verbose_name=_('is_archived_field')
    )

    class Meta:
        db_table = 'home_news'
        ordering = ['-date']
        verbose_name = _('News')
        verbose_name_plural = _('Newss')

    def __unicode__(self):
        if self.language_code:
            return self.title
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)

    def __str__(self):
        if self.language_code:
            return self.title
        else:
            return '{} (ID: {})'.format(self.__class__.__name__, self.pk)


# Define choices for settingstype
SETTINGSTYPE_CHOICES = (
    (1, _("Slider Item")),
    (2, _("Menu Link")),
    (3, _("Meta Tag")),
    (4, _("Advertising Item")),
    (5, _("Script Reference")),
    (6, _("Template Item"))
)


# Define choices for settingstype
VALUETYPE_CHOICES = (
    (1, _("String")),
    (2, _("List")),
    (3, _("Dictionary")),
    (4, _("Translation")),
    (5, _("StaticURL")),
    (6, _("MediaURL")),
    (7, _("URLResolver")),
    (8, _("Script"))
)


# Hint: Making existing fields translatable,
# see https://django-parler.readthedocs.io/en/latest/advanced/migrating.html
# Model for translations of WebsiteSettings
class WebsiteSettingsLocals(TranslatableModel):
    msgid = models.CharField(
        max_length=191,
        verbose_name=_('msgid_field')
    )
    translations = TranslatedFields(
        msgstr=models.TextField(
            blank=True,
            null=True,
            verbose_name=_('msgstr_field')
        ),
    )

    class Meta:
        db_table = 'home_websitesettingslocals'
        verbose_name = _('Website settings locale')
        verbose_name_plural = _('Website settings locales')

    def __unicode__(self):
        return self.msgid

    def __str__(self):
        return self.msgid


# Model for scripts of WebsiteSettings
class WebsiteSettingsScripts(models.Model):
    name = models.CharField(
        max_length=191,
        unique=True,
        verbose_name=_('name_field')
    )
    content_type = models.CharField(
        max_length=191,
        verbose_name=_('content_type_field')
    )
    body = models.TextField(
        verbose_name=_('body_field')
    )
    description = models.CharField(
        max_length=191,
        blank=True,
        null=True,
        verbose_name=_('description_field')
    )

    class Meta:
        db_table = 'home_websitesettingsscripts'
        verbose_name = _('Website settings scripts')
        verbose_name_plural = _('Website settings scriptss')

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


# Model for Settings
class Settings(TimeStampedModelMixin):
    name = models.CharField(
        max_length=30,
        verbose_name=_('name_field')
    )
    json = JSONField(
        verbose_name=_('json_field')
    )
    is_archived = models.BooleanField(
        default=False,
        verbose_name=_('is_archived_field')
    )

    class Meta:
        db_table = 'home_appsettings'
        verbose_name = _('Settings')
        verbose_name_plural = _('Settingss')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


# Model for audit logging of registered models by reversion
class RevisionAudit(TimeStampedModelMixin):
    object_id = models.CharField(
        max_length=191,
        help_text="Primary key of the model under version control.",
    )
    object_repr = models.TextField(
        help_text="Pseudo name of the model under version control.",
    )
    content_type = models.ForeignKey(
        ContentType,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="Content type of the model under version control.",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("User"),
        help_text="The user who created this revision.",
    )
    action = models.CharField(
        max_length=20,
        help_text="The database action for this revision.",
    )
    comment = models.TextField(
        blank=True,
        verbose_name=_("Comment"),
        help_text="A text comment on this revision.",
    )
    version = models.ForeignKey(
        Version,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The object that contains this version.",
    )

    class Meta:
        db_table = 'revision_audit'
        ordering = ['-created']
        verbose_name = _('Revision Audit')
        verbose_name_plural = _('Revision Audits')

    def __str__(self):
        return '{} (ID: {}, Version: {})'.format(
            self.content_type,
            self.object_id,
            self.version.pk if self.version else ''
        )

    def __unicode__(self):
        return '{} (ID: {}, Version: {})'.format(
            self.content_type,
            self.object_id,
            self.version.pk if self.version else ''
        )

mywebsite_home/forms.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from captcha.fields import CaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.shortcuts import reverse
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm
from reversion.models import Version

from mywebsite.utils.widgets import AceWidget, JSONEditorWidget, TinyMCEWidget
from mywebsite_antispam.honeypot.forms import HoneypotField
from mywebsite_antispam.spamdetector.forms import SpamDetectorField

from . import models


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    url = HoneypotField()
    message = SpamDetectorField(required=True, widget=forms.Textarea, max_length=2048)
    captcha = CaptchaField()  # required=True must be set via jQuery in template, because of CaptchaField

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'ajax-form-contact'
        self.helper.form_class = 'form-validate well'
        self.helper.form_method = 'POST'
        self.helper.form_action = reverse('home:contact')
        self.helper.attrs.update({'novalidate': ''})
        # translation for fields
        self.fields['contact_name'].label = _('contact_name')
        self.fields['contact_email'].label = _('contact_email')
        self.fields['message'].label = _('contact_message')
        self.fields['captcha'].label = _('contact_captcha')
        # add submit button
        self.helper.add_input(Submit('submit', _("CONTACT_SUBMIT"), css_class="btn btn-dark text-white"))


class NewsAdminForm(TranslatableModelForm):
    body = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ))

    class Meta:
        model = models.News
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(NewsAdminForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = _('body_field')


class ScriptsEditorAdminForm(forms.ModelForm):
    class Meta:
        model = models.WebsiteSettingsScripts
        widgets = {
            'body': AceWidget(
                mode="css",
                theme="tomorrow_night_eighties",
                width="100%",
                height="500px",
                showprintmargin=True,
            ),
        }
        exclude = ()


class VersionAdminForm(forms.ModelForm):
    class Meta:
        model = Version
        widgets = {
            'serialized_data': JSONEditorWidget
        }
        exclude = ()

mywebsite_home/templates/home/base.html
<!--
	Copyright (C) 2018 dsoft-app-dev.de and friends.

	This Program may be used by anyone in accordance with the terms of the
	German Free Software License

	The License may be obtained under http://www.d-fsl.org.
-->

{% load i18n static cookielaw_tags simple_menu core_settings_tags websettings_tags %}
{% load render_bundle from webpack_loader %}
{% generate_simple_menu %}

<!DOCTYPE html>
<html lang="de">

<head>
    <title>{% transFromWebSettings "WEBSITE_TITLE" %}</title>
    <meta charset="utf-8">
    <!-- Include Floating Social Buttons -->
    <meta
        property="floatingSocialButtons"
        content="{% site_vars as vars %} {{ vars.FLOATING_SOCIAL_BUTTONS }}"
    />
    <meta
        http-equiv="X-UA-Compatible"
        content="IE=edge"
    >
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    >
    <!-- Add to Home Screen for iOS -->
    <meta
        name="apple-mobile-web-app-capable"
        content="yes"
    >
    <!-- Placeholder for extra header content from templates -->
    {% block head %} {% include "home/includes/meta-tags.html" %} {% endblock %}
    {% render_bundle 'appStyle' skip_common_chunks=True suffix='' %}
    {% getCoreSettingItemsFor _('Script Reference') 'App Stylesheets' as object_list %}
    {% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
    {% if obj|getAttribItemKey == "href" %}
    <link
        rel="stylesheet"
        href="{{ obj|getAttribItemValue|handleWebSettingsType }}"
    >
    {% else %}
    <style>
        {% autoescape off %}
            {{ obj|getAttribItemValue|handleWebSettingsType }}
        {% endautoescape %}
    </style>
    {% endif %}
    {% endfor %}
    {% endfor %}
    <!-- Placeholder for extra styling from templates -->
    {% block extrastyle %} {% endblock %}
    <!-- Include of matomo tracking tags -->
    {% if "home/includes/matomo-tracking.html"|template_exists %}
    {% include_maybe "home/includes/matomo-tracking.html" %}
    {% endif %}
</head>

<body>
    <noscript>
        <!-- Check if Javascript is enabled -->
        <div
            id="nojs"
            class="overlay"
        >
            <div class="popup">
                <h2>{% trans "NOSCRIPT_HEADER" %}</h2>
                <a
                    class="close"
                    href="#nojs"
                >&times;</a>
                <div class="content">
                    {% trans "NOSCRIPT_INFO_TEXT" %}
                    <a
                        class="alert-link"
                        href="https://www.enable-javascript.com/"
                        target="_blank"
                    >{% trans "NOSCRIPT_INFO_REF" %}.</a>
                </div>
            </div>
        </div>
    </noscript>
    <script
        src="{% url 'javascript-catalog' %}"
        type="text/javascript"
    ></script>
    {% render_bundle 'app' skip_common_chunks=True suffix='' %}
    {% getCoreSettingItemsFor _('Script Reference') 'App Javascripts' as object_list %}
    {% for object in object_list %}
    {% for obj in object|getWebSettingsAttribItems %}
    {% if obj|getAttribItemKey == "src" %}
    <script
        src="{{ obj|getAttribItemValue|handleWebSettingsType }}"
        type="text/javascript"
    ></script>
    {% else %}
    <script type="text/javascript">
        {% autoescape off %}
            {{ obj|getAttribItemValue|handleWebSettingsType }}
        {% endautoescape %}
    </script>
    {% endif %}
    {% endfor %}
    {% endfor %}
    <!-- Placeholder for extra javascript block from templates -->
    {% block javascript %}
    {% endblock %}
    <!-- Include Cookie banner -->
    {% cookielaw_banner %}
    <div id="menuModal">
        <div class="modal-content">
            <div class="container_12">
                <div class="grid_12">
                    <div
                        id="btn-close-modal"
                        class="close-menuModal modCloseButton"
                    >
                        <span></span>
                    </div>
                </div>
            </div>
            <div id="navigation-res">
                <div class="container_12">
                    <div class="grid_12">
                        {% include 'home/includes/menu.html' with menu=menus.main %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="search">
        <a
            href="#"
            class="cd-popup-trigger"
        >
            <i class="fa fa-search"></i>
        </a>
        <div
            class="cd-popup"
            role="alert"
        >
            <div class="cd-popup-container">
                <div class="search">
                    {% include "home/includes/search.html" %}
                </div>
                <a
                    href="#0"
                    class="cd-popup-close img-replace"
                >{% trans "SEARCH_INFO_CLOSE" %}</a>
            </div>
        </div>
    </div>

    <div class="page">
        <div id="header">
            <div class="container_12">
                <div class="grid_3">
                    <div id="sitename">
                        <a href="{% url 'home:index' %}">
                            <img
                                src="{% static 'mywebsite/img/logo.png' %}"
                                alt="Daßler Software Application Development"
                                width="250"
                                height="144"
                            >
                        </a>
                    </div>
                </div>
                <div class="grid_1">
                    <div class="menuButton">
                        <a
                            id="openMenu"
                            href="#menuModal"
                        ></a>
                    </div>
                </div>
                <div class="grid_8">
                    <div id="nav-top">
                        <div id="navigation">
                            {% include 'home/includes/menu.html' with menu=menus.main %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid_12">
            <div class="col-right">
                <div id="parallax">
                    {% include "home/includes/parallax-image.html" %}
                </div>
                <div class="clr"></div>

                {% block content %} {% endblock %}

                <div id="parallax-slider">
                    {% include "home/includes/parallax-slider.html" %}
                </div>
                <div class="clr"></div>

                <div id="block-bottomcontent">
                    {% include "home/includes/bottom-content.html" %}
                </div>

                <div id="block-footer">
                    <div class="container_12">
                        <div class="grid_6">
                            <div
                                class="copyright"
                                data-scrollreveal="enter top over 0.8s"
                            >
                                {% transFromWebSettings "WEBSITE_DEV_FOOTER" %}
                            </div>
                        </div>
                        <div class="grid_6">
                            <div class="soc_icons_box">
                                <ul
                                    class="soc_icons"
                                    data-scrollreveal="enter left over 0.8s"
                                >
                                    <li>
                                        <!-- <a href="https://www.linkedin.com/in/chris-daßler-b3964a160" class="fa fa-linkedin" target="_blank" rel="nofollow" /> -->
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a
                href="#"
                class="back-to-top"
            >{% trans "WEBSITE_BACK_TO_TOP" %}</a>
        </div>
    </div>
</body>

</html>

mywebsite_home/templates/home/contact.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static crispy_forms_tags %}

{% block extrastyle %}
<style>
    #div_id_captcha img {
        margin: 0 !important;
        padding-bottom: 7px !important;
    }

    .captcha-refresh {
        margin: 0px 0px 0px 5px;
    }

    .invalid-feedback {
        display: inline-block;
    }

</style>
{% endblock %}

{% block content %}
<section id="content">
    <div class="contact">
        <h1>{% trans "CONTACT_HEADING" %}</h1>
        <div class="separator"></div>
        <div id="slide-contact">
            <div class="messages">
                <!-- Here is the space for messages -->
            </div>
            {% crispy form %}
        </div>
    </div>
</section>
{% endblock %}

mywebsite_home/templates/home/index.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="newsfeed news">
        <h1>{% trans "INDEX_TITLE" %}</h1>
        <div class="separator"></div>
        {% for news in news_list %}
        <div class="article-blog post">
            <div class="meta">
                {{ news.date|date:"d M Y" }}
                {% if news.category %}
                / <a href="{% url 'blog:article-category-list' category=news.category.slug %}">{{ news.category }}</a>
                {% endif %}
            </div>
            {% if not news.is_body_title_hidden %}
            <h3 class="article-header-blog">
                {% if news.slug %}
                <a href="{% url 'blog:article-detail' slug=news.slug %}">
                    {{ news.title }}
                </a>
                {% else %}
                {{ news.title }}
                {% endif %}
            </h3>
            {% else %}
            <div class="separator"></div>
            {% endif %}
            <div class="teaser">
                {% if news.teaser %}
                {{ news.teaser|safe }}
                {% else %}
                {{ news.body|safe }}
                {% endif %}
            </div>
            {% if news.slug %}
            <h6 class="more">
                <a href="{% url 'blog:article-detail' slug=news.slug %}">
                    {% trans "ARTICLE_LIST_READ_MORE" %}
                </a>
            </h6>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    {% block pagination %} {% if is_paginated %}
    {% include "home/includes/pagination.html" %}
    {% endif %} {% endblock %}
</section>
{% endblock %}

mywebsite_home/templates/home/search-results.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="article-list">
        <h1>{% trans "SEARCH_RESULTS_HEADING" %}</h1>
        <div class="separator"></div>
        <div class="article-list">
            {% if article_list %} {% for article in article_list %}
            <div class="article-blog post">
                <div class="meta">
                    {{ article.date|date:"d M Y" }} /
                    <a href="{% url 'blog:article-category-list' category=article.category.slug %}">{{ article.category }}</a>
                </div>
                <h2 class="article-header-blog">
                    <a href="{% url 'blog:article-detail' slug=article.slug %}">
                        {{ article.title }}
                    </a>
                </h2>
                <div class="teaser">
                    {{ article.teaser|safe }}
                </div>
                <h6 class="more">
                    <a href="{% url 'blog:article-detail' slug=article.slug %}">
                        {% trans "ARTICLE_LIST_READ_MORE" %}
                    </a>
                </h6>
            </div>
            {% endfor %} {% else %}
            <p>{% trans "SEARCH_NORESULTS" %}</p>
            {% endif %}
        </div>
    </div>
    {% block pagination %} {% if is_paginated %}
    {% include "home/includes/pagination.html" %}
    {% endif %} {% endblock %}
</section>
{% endblock %}