mywebsite/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

from filebrowser.sites import site

from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.ico')),  # https://favicon.io/favicon-generator/
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include('django_otp.urls')),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
    path('maintenance-mode/', include('maintenance_mode.urls')),
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name='admin-manual'),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite_blog/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.urls import include, path

from . import views

app_name = 'blog'

urlpatterns = [
    # Categories
    path('category', views.CategoryListView.as_view(), name='category'),
    path('category/<slug:category>', views.ArticleListView.as_view(), name='article-category-list'),

    # Tags
    path('tags/get-list-flat', views.get_tags_list_flat_jx, name='get-tags-list-flat'),
    path('tags/<tagname>', views.ArticleListView.as_view(), name='article-tag-list'),

    # Articles
    path('', views.ArticleListView.as_view(), name='blog'),
    path('<slug:slug>', views.ArticleDetailView.as_view(), name='article-detail'),
    path('<slug:slug>/compare', views.ArticleHistoryCompareDetailView.as_view(), name='compare-article'),
]

mywebsite_blog/forms.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django import forms
from django.utils.translation import gettext_lazy as _
from parler.forms import TranslatableModelForm

from mywebsite.utils.widgets import TinyMCEWidget

from . import models
from .templatetags.blog_tags import unescape_raw


class ArticleAdminForm(TranslatableModelForm):
    body = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ),
        required=False
    )
    teaser = forms.CharField(widget=TinyMCEWidget(
        attrs={'cols': 30, 'rows': 10}
    ))
    tags = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': _('Add tags separated by comma')}
    ),
        required=False
    )

    class Meta:
        model = models.Article
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ArticleAdminForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = _('body_field')
        self.fields['teaser'].label = _('teaser_field')
        self.fields['tags'].label = _('tags_field')
        # unescape 'tags'
        if self.instance.id and self.instance.tags:
            self.initial['tags'] = unescape_raw(self.instance.tags)

mywebsite_blog/views.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

import operator
from datetime import datetime

from django.conf import settings
from django.core.paginator import EmptyPage, Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.utils import http, translation
from django.utils.translation import get_language
from django.utils.translation import gettext as _
from django.views import generic

from hitcount.views import HitCountDetailView
from reversion_compare.views import HistoryCompareDetailView

from mywebsite.utils.tools import get_default_language, tinymce_word_count
from mywebsite_blog.templatetags.blog_tags import unescape_raw
from mywebsite_home.templatetags.core_settings_tags import getCoreSettingItemsFor
from mywebsite_home.templatetags.websettings_tags import handleWebSettingsType

from .models import Article, ArticleTag, Category


# Commond data & querys used to view/create/edit articles
def common_article_data(extra_context=None):
    # Static data
    lang_code = translation.get_language()
    # Querys
    article_tags = ArticleTag.objects.filter(lang_code=lang_code,
                                             article__is_published=True,
                                             article__is_archived=False).order_by(
        'name').distinct().values_list('name', flat=True)

    # set context
    context = {'lang_code': lang_code, 'article_tags': article_tags}

    # Extra context - merge context dict and extra_context dict to context dict
    if extra_context:
        context = {**extra_context, **context}

    return context


def getSlugByMenuItemName(link_name=None):
    # Collect WebSettings for this menu link
    result_list = getCoreSettingItemsFor(settingstype=_('Menu Link'), name='Menu Items')

    if link_name:
        # Get exact menu item by containing string
        slug_itmes = [item['slug'] for item in result_list if link_name in item['name']]
    else:
        # Get all menu items
        slug_itmes = [{'name': item['name'], 'slug': handleWebSettingsType(item['slug'])} for item in result_list]

    data = []
    if slug_itmes:
        data = slug_itmes

    return data


def getArticleByMenuItemName(link_name):
    # Get exact slug by containing string
    slug_items = getSlugByMenuItemName(link_name)

    data = None
    if slug_items:
        # Get first object from list. Btw., we should always have only one object when using link_name!
        slug = slug_items[0]

        # We are using the blog app instead of a fixed template
        # data = Article.objects.active_translations().distinct().get(
        #     slug__iexact=handleWebSettingsType(slug), is_internal=True, is_archived=False)
        # TODO: django-parler has a bug here! We have manually retrieve the fallback language not to run into error 500
        current_lang = get_language()
        fallback_lang = get_default_language()
        try:
            data = Article.objects.translated(current_lang).get(
                slug__iexact=handleWebSettingsType(slug), is_internal=True, is_archived=False)
        except Article.DoesNotExist:
            data = Article.objects.translated(fallback_lang).get(
                slug__iexact=handleWebSettingsType(slug), is_internal=True, is_archived=False)
    return data


class CustomPaginator(Paginator):
    def validate_number(self, number):
        try:
            return super().validate_number(number)
        except EmptyPage:
            if int(number) > 1:
                # return the last page
                return self.num_pages
            elif int(number) < 1:
                # return the first page
                return 1
            else:
                raise


class ArticleCommonDataMixin(object):
    def get_context_data(self, **kwargs):
        context = super(ArticleCommonDataMixin, self).get_context_data(**kwargs)
        # add common_article_data to context
        for key, value in common_article_data().items():
            if callable(value):
                context[key] = value()
            else:
                context[key] = value
        return context


class ArticleListView(ArticleCommonDataMixin, generic.ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'blog/article_list.html'
    paginate_by = settings.PAGINATION_ARTICLES
    paginator_class = CustomPaginator

    def render_to_response(self, context, **response_kwargs):
        response = super(ArticleListView, self).render_to_response(context, **response_kwargs)
        # set cookie for FORCE_SCRIPT_NAME setting, because this is used for TinyMCE CustomFileBrowser's callback
        response.set_cookie("force_script_name", settings.FORCE_SCRIPT_NAME)
        return response

    def get_queryset(self):
        queryset = super(ArticleListView, self).get_queryset()
        # standard filter
        queryset = queryset.active_translations().distinct().filter(is_published=True,
                                                                    is_archived=False,
                                                                    date__lte=datetime.now()).order_by('-date')
        # additional filter through url request
        if self.kwargs and 'category' in self.kwargs:
            # request was 'article-category-list'
            category_filter = self.kwargs['category']
            if category_filter:
                queryset = queryset.filter(category__slug=category_filter)

        if self.kwargs and 'tagname' in self.kwargs:
            # request was 'article-tag-list'
            tag_filter = self.kwargs['tagname']
            if tag_filter:
                queryset = queryset.filter(tags_rel__name=tag_filter)
        return queryset


class ArticleDetailView(ArticleCommonDataMixin, HitCountDetailView):
    context_object_name = 'article'
    template_name = 'blog/article.html'
    model = Article
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)

        # calculate article read time
        if self.object.body:
            context['body_word_count'] = tinymce_word_count(self.object.body)
        else:
            context['body_word_count'] = 0
        if self.object.teaser:
            context['teaser_word_count'] = tinymce_word_count(self.object.teaser)
        else:
            context['teaser_word_count'] = 0
        return context


class CategoryListView(ArticleCommonDataMixin, generic.ListView):
    model = Category
    context_object_name = 'category_list'
    template_name = 'blog/category_list.html'
    paginate_by = settings.PAGINATION_CATEGORIES
    paginator_class = CustomPaginator

    def get_queryset(self):
        queryset = super(CategoryListView, self).get_queryset()
        queryset = queryset.active_translations().distinct().filter(is_internal=False, is_published=True,
                                                                    is_archived=False, date__lte=datetime.now())
        # .order_by('translations__name') doesn't work, because it multiplies entries by using .active_translations()
        queryset = sorted(queryset, key=operator.attrgetter('name'))
        return queryset


class ArticleHistoryCompareDetailView(ArticleCommonDataMixin, HistoryCompareDetailView):
    model = Article
    template_name = 'blog/article_compare.html'


class AjaxArticleDetailView(ArticleCommonDataMixin, generic.TemplateView):
    link_name = None
    template_name = 'blog/article_ajax.html'

    def get_context_data(self, **kwargs):
        context = super(AjaxArticleDetailView, self).get_context_data(**kwargs)
        context = {**{'article': getArticleByMenuItemName(self.link_name)}, **context}
        return context


def get_tags_list_flat_jx(request):
    lang_code = request.POST.get('language', get_default_language())
    data = list()
    for item in ArticleTag.objects.filter(lang_code=lang_code).order_by('name').distinct().values_list('name', flat=True):
        data.append(unescape_raw(item))

    return JsonResponse(data, safe=False)

mywebsite_blog/templates/blog/article.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static blog_tags core_settings_tags websettings_tags %}

{% block head %}
<meta
    name="keywords"
    content="{{ article.meta_keywords|safe }}"
>
<meta
    name="description"
    content="{{ article.teaser|striptags|safe }}"
>
<meta
    name="author"
    content="{{ article.author|safe }}"
>
<!-- Google / Search Engine Tags -->
<meta
    itemprop="name"
    content="{{ article.title|safe }}"
>
<meta
    itemprop="description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Google Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'image'|getAttribItemValue|handleWebSettingsType as google_image %}
<meta
    itemprop="image"
    content="{{ google_image }}"
>
{% endwith %}
<!-- Facebook Meta Tags -->
<meta
    property="og:url"
    content="{{ request.build_absolute_uri }}"
>
<meta
    property="og:type"
    content="article"
>
<meta
    property="og:title"
    content="{{ article.title|safe }}"
>
<meta
    property="og:description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Facebook Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'og:image'|getAttribItemValue|handleWebSettingsType as og_image %}
<meta
    property="og:image"
    content="{{ og_image }}"
>
{% endwith %}
<meta
    property="og:locale"
    content="de_DE"
>
<!-- Twitter Meta Tags -->
<meta
    name="twitter:card"
    content="summary"
>
<meta
    name="twitter:url"
    content="{{ request.build_absolute_uri }}"
>
<meta
    name="twitter:title"
    content="{{ article.title|safe }}"
>
<meta
    name="twitter:description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Twitter Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'twitter:image'|getAttribItemValue|handleWebSettingsType as twitter_image %}
<meta
    name="twitter:image"
    content="{{ twitter_image }}"
> {% endwith %}
{% endblock %}

{% block javascript %}
{% endblock %}

{% block content %}
<section id="content">
    <div class="article-blog single">
        <aside>
            <time class="day">{{ article.date|date:"d M Y" }}</time>
        </aside>
        {% if not article.is_body_title_hidden %}
        <h2 class="article-header-blog">
            {{ article.title }}
        </h2>
        {% endif %}
        <div class="block-info">
            <span class="article-info">
                <dt class="article-info-term">{% trans "ARTICLE_INFO_DETAILS" %}</dt>
                <dt class="article-info-term">{% trans "ARTICLE_INFO_HITS" %}: </dt>
                <dd class="hits">{{ hitcount.total_hits }}</dd>
            </span>
        </div>
        {% if not article.is_internal %}
        <div class="separator"></div>
        <div class="meta">{% trans "ARTICLE_READ_TIME" %}: ~ {{ body_word_count|minutes }} {% trans "minutes" %},
        {{ body_word_count|seconds }} {% trans "seconds" %} / {{ lang_code }}
        </div>
        {% for tag in article_tags %}
        <a href="{% url 'blog:article-tag-list' tagname=tag %}">{{ tag|unescape_raw }}</a>
        {% endfor %}
        {% endif %}
        <div class="separator"></div>
        <div class="content-text">
            {{ article.body|safe }}
        </div>
    </div>
</section>
{% endblock %}

mywebsite_blog/templates/blog/article_ajax.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static hitcount_tags core_settings_tags websettings_tags %}

{% block head %}
<meta
    name="keywords"
    content="{{ article.meta_keywords|safe }}"
>
<meta
    name="description"
    content="{{ article.teaser|striptags|safe }}"
>
<meta
    name="author"
    content="{{ article.author|safe }}"
>
<!-- Google / Search Engine Tags -->
<meta
    itemprop="name"
    content="{{ article.title|safe }}"
>
<meta
    itemprop="description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Google Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'image'|getAttribItemValue|handleWebSettingsType as google_image %}
<meta
    itemprop="image"
    content="{{ google_image }}"
>
{% endwith %}
<!-- Facebook Meta Tags -->
<meta
    property="og:url"
    content="{{ request.build_absolute_uri }}"
>
<meta
    property="og:type"
    content="article"
>
<meta
    property="og:title"
    content="{{ article.title|safe }}"
>
<meta
    property="og:description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Facebook Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'og:image'|getAttribItemValue|handleWebSettingsType as og_image %}
<meta
    property="og:image"
    content="{{ og_image }}"
>
{% endwith %}
<meta
    property="og:locale"
    content="de_DE"
>
<!-- Twitter Meta Tags -->
<meta
    name="twitter:card"
    content="summary"
>
<meta
    name="twitter:url"
    content="{{ request.build_absolute_uri }}"
>
<meta
    name="twitter:title"
    content="{{ article.title|safe }}"
>
<meta
    name="twitter:description"
    content="{{ article.teaser|striptags|safe }}"
>
{% getCoreSettingItemsFor _('Meta Tag') 'Twitter Tags' as object_list %}
{% with object_list|getWebSettingsNamedAttrib:'twitter:image'|getAttribItemValue|handleWebSettingsType as twitter_image %}
<meta
    name="twitter:image"
    content="{{ twitter_image }}"
> {% endwith %}
{% endblock %}

{% block javascript %}
{% get_hit_count_js_variables for article as hitcount %}
<script type="text/javascript">
    let $hitcount_pk = "{{ hitcount.pk }}",
        $hitcount_url = "{{ hitcount.ajax_url }}";

</script>
{% endblock %}

{% block content %}
<section id="content">
    <div class="article-blog ajax single">
        <aside>
            <time class="day">{{ article.date|date:"d M Y" }}</time>
        </aside>
        {% if not article.is_body_title_hidden %}
        <h2 class="article-header-blog">
            {{ article.title }}
        </h2>
        {% endif %}
        {% get_hit_count for article as total_hits %}
        <div class="block-info">
            <span class="article-info">
                <dt class="article-info-term">{% trans "ARTICLE_INFO_DETAILS" %}</dt>
                <dt class="article-info-term">{% trans "ARTICLE_INFO_HITS" %}: </dt>
                <dd class="hits">{{ total_hits }}</dd>
            </span>
        </div>
        <div class="separator"></div>
        <div class="content-text">
            {{ article.body|safe }}
        </div>
    </div>
</section>
{% endblock %}

mywebsite_blog/templates/blog/article_compare.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block extrastyle %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'mywebsite/css/admin-extra.css' %}"
/>
<style>
    input {
        background: #262626;
        color: #fff !important;
        border: none;
        padding: 10px;
        margin: 20px 0;
        border-radius: 0;
    }

</style>
{% endblock %}

{% block content %}
<section id="content">
    <div class="article-history-list">
        <h1>{% trans "ARTICLE_COMPARE_HISTORY" %}</h1>
        <div class="separator"></div>
        <div class="diff">
            <div class="meta">
                <a href="{% url 'blog:article-detail' slug=article.slug %}">{{ article.title }}</a> / {{ article.date|date:"d M Y" }}
                /
                <a href="{% url 'blog:article-category-list' category=article.category.slug %}">{{ article.category }}</a>
            </div>
            <div>
                {% include "reversion-compare/action_list_partial.html" %}
            </div>
            <div>
                {% if request.GET.version_id1 %}
                <div> {% include "reversion-compare/compare_partial.html" %} </div>
                <div> {% include "reversion-compare/compare_links_partial.html" %} </div>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

mywebsite_blog/templates/blog/article_list.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="separator"></div>
    <div class="article-list">
        {% if article_list %} {% for article in article_list %}
        <div class="article-blog post">
            <div class="meta">
                {{ article.date|date:"d M Y" }} /
                <a href="{% url 'blog:article-category-list' category=article.category.slug %}">{{ article.category }}</a>
            </div>
            <h2 class="article-header-blog">
                <a href="{% url 'blog:article-detail' slug=article.slug %}">
                    {{ article.title }}
                </a>
            </h2>
            <div class="teaser">
                {{ article.teaser|safe }}
            </div>
            <h6 class="more">
                <a href="{% url 'blog:article-detail' slug=article.slug %}">
                    {% trans "ARTICLE_LIST_READ_MORE" %}
                </a>
            </h6>
        </div>
        {% endfor %} {% else %}
        <p>{% trans "SEARCH_NORESULTS" %}</p>
        {% endif %}
    </div>
    {% block pagination %} {% if is_paginated %}
    {% include "home/includes/pagination.html" %}
    {% endif %} {% endblock %}
</section>
{% endblock %}

mywebsite_blog/templates/blog/category_list.html
{% extends 'home/base.html' %}

{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="categories-list">
        <h1>{% trans "MENU_CATEGORIES" %}</h1>
        <div class="separator"></div>
        <ul class="first">
            {% for category in category_list %}
            <li>
                <span class="item-title">
                    <a href="{% url 'blog:article-category-list' category=category.slug %}">{{ category.name }}</a>
                    <span
                        class="badge badge-info tip"
                        data-toggle="tooltip"
                        title="{% trans 'Article count' %}: {{ category.articles.count }}"
                    >
                        {{ category.articles.count }}
                    </span>
                </span>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% block pagination %} {% if is_paginated %}
    {% include "home/includes/pagination.html" %}
    {% endif %} {% endblock %}
</section>
{% endblock %}